language: node_js
language: python
python:
  - "3.6"
branches:
  only:
  - master
  - stage
git:
  submodules: false
before_install:
  # 让 travis ci 可以使用 git submodule，这要求 git submodule 的格式必须是 https 的
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git submodule update --init --recursive
before_script:
  - yarn install
cache:
  yarn: true
script:
  - ./preDeploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_USER_TOKEN
  repo: SwiftGGSite/SwiftGGSite.github.io
  target-branch: master
  local-dir: public
  keep-history: true
  on:
    branches:
      only:
         - stage
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $CI_USER_TOKEN
  repo: SwiftGG/SwiftGGTeam.github.io
  target-branch: master
  local-dir: public
  keep-history: true
  on:
    branches:
      only:
        - master